#! /usr/bin/env bash

set -e

. auto/common

echo "settings check:"
echo "mirror=\"$mirror\""
echo "mirror_packages\"$mirror_packages\""
echo "unstable=\"$unstable\""
echo "stable=\"$stable\""
echo "bootstrapopts=\"$bootstrapopts\""
echo "usekeyring=\"$usekeyring\""
echo "distromode=\"$distromode\""
echo "dsusekeyring=\"$dsusekeyring\""
echo "nonfree=\"$nonfree\""
echo "hardened=\"$hardened\""
echo "proxy_addr=\"$proxy_addr\""
echo "useproxy=\"$useproxy\""
echo "customize=\"$customize\""
echo "server=\"$server\""

lb clean

lb build noauto "$@" > >(tee -a log) 2> >(tee -a err >&2) || bash
#lb build noauto "$@" > >(tee -a log) 2> >(tee -a err >&2)

