#! /usr/bin/env bash

set -e

. auto/common

echo "settings check:" > >(tee -a config.log) 2> >(tee -a config.err >&2)
echo "mirror=\"$mirror\"" > >(tee -a config.log) 2> >(tee -a config.err >&2)
echo "mirror_packages\"$mirror_packages\"" > >(tee -a config.log) 2> >(tee -a config.err >&2)
echo "unstable=\"$unstable\"" > >(tee -a config.log) 2> >(tee -a config.err >&2)
echo "stable=\"$stable\"" > >(tee -a config.log) 2> >(tee -a config.err >&2)
echo "components='$components'" > >(tee -a config.log) 2> >(tee -a config.err >&2)
echo "nosource=\"$nosource\"" > >(tee -a config.log) 2> >(tee -a config.err >&2)
echo "archiveareas=\"$archiveareas\"" > >(tee -a config.log) 2> >(tee -a config.err >&2)
echo "useupdates=\"$useupdates\"" > >(tee -a config.log) 2> >(tee -a config.err >&2)
echo "deboostrap_opts_supported=\"$debootstrap_opts_supported\"" > >(tee -a config.log) 2> >(tee -a config.err >&2)
echo "image_name=\"$image_name\"" > >(tee -a config.log) 2> >(tee -a config.err >&2)
echo "image_name_supported=\"$image_name_supported\"" > >(tee -a config.log) 2> >(tee -a config.err >&2)
echo "bootstrapopts=\"$bootstrapopts\"" > >(tee -a config.log) 2> >(tee -a config.err >&2)
echo "usekeyring=\"$usekeyring\"" > >(tee -a config.log) 2> >(tee -a config.err >&2)
echo "distromode=\"$distromode\"" > >(tee -a config.log) 2> >(tee -a config.err >&2)
echo "dsusekeyring=\"$dsusekeyring\"" > >(tee -a config.log) 2> >(tee -a config.err >&2)
echo "nonfree=\"$nonfree\"" > >(tee -a config.log) 2> >(tee -a config.err >&2)
echo "non_free=\"$non_free\"" > >(tee -a config.log) 2> >(tee -a config.err >&2)
echo "hardened=\"$hardened\"" > >(tee -a config.log) 2> >(tee -a config.err >&2)
echo "is_harden=\"$is_harden\"" > >(tee -a config.log) 2> >(tee -a config.err >&2)
echo "proxy_addr=\"$proxy_addr\"" > >(tee -a config.log) 2> >(tee -a config.err >&2)
echo "useproxy=\"$useproxy\"" > >(tee -a config.log) 2> >(tee -a config.err >&2)
echo "custom=\"$custom\"" > >(tee -a config.log) 2> >(tee -a config.err >&2)
echo "customized=\"$customized\"" > >(tee -a config.log) 2> >(tee -a config.err >&2)
echo "server=\"$server\"" > >(tee -a config.log) 2> >(tee -a config.err >&2)
echo "serverdist=\"$serverdist\"" > >(tee -a config.log) 2> >(tee -a config.err >&2)

sleep 10

lb clean noauto "$@" > >(tee -a log) 2> >(tee -a err >&2) || bash

lb build noauto "$@" > >(tee -a log) 2> >(tee -a err >&2) || bash
#lb build noauto "$@" > >(tee -a log) 2> >(tee -a err >&2)

