#! /usr/bin/env bash

set -e

lb clean noauto #"$@"

#rm -rf config/binary \
#        config/build \
#        config/bootstrap \
#        config/chroot \
#        config/common \
#        config/source

#rm -rf *.hybrid.iso \
#	*.hybrid.iso.sha256sum \
#	*.hybrid.iso.sha256sum.asc \
#	*.files \
#	*.contents \
#	*.hybrid.iso.zsync \
#	*.packages \
#	*log \
 #       *err
