#! /usr/bin/env bash

components=$( [ ! -z "$nonfree" ] && echo "--components=\"main,contrib,non-free\"" || echo "" )

if [ ! -z "$components" ]; then
        echo "WARNING: USING NON-FREE COMPONENTS! $components"
        sleep 5
fi

lb config noauto \
    -b iso-hybrid \
    --debian-installer live \
    --system live \
    --apt-http-proxy http://192.168.2.203:3142 \
    -d sid \
    --updates no \
    --parent-distribution sid \
    --debootstrap-options "--merged-usr --variant=minbase --include=busybox-syslogd,gnupg2,gpgv-static,gnutls-bin $components" \
    --initsystem sysvinit \
    --parent-mirror-bootstrap http://ftp.us.debian.org/debian/ \
    "$@"
