#! /usr/bin/env bash

components=$( [ ! -z "$nonfree" ] && echo "--components=\"main,contrib,non-free\"" || echo "" )
archiveareas=$( [ ! -z "$nonfree" ] && echo "--archive-areas=\"main,contrib,non-free\"" || echo "" )
nosource=$( [ ! -z "$nonfree" ] && echo "--apt-source-archives false" || echo "" )

export non_free=$( [ ! -z "$nonfree" ] && echo "-nonfree" || echo "" )

useproxy=$( [ ! -z "$proxy_addr" ] && echo "--apt-http-proxy $proxy_addr" || echo "" )
harden=$( [ ! -z "$hardened" ] && echo "-k grsec-amd64" || echo "" )

export is_harden=$( [ ! -z "$hardened" ] && echo "-hardened" || echo "" )
export customized=$( [ ! -z "$customize" ] && echo "-custom" || echo "" )


dsusekeyring="--keyring=$HOME/.gnupg/repokeys.gpg"
usekeyring="--keyring-packages debian-keyring,debian-archive-keyring"
mirror='http://ftp.us.debian.org/debian/'
bootstrapopts="--merged-usr $dsusekeyring --variant=minbase --include=busybox-syslogd,gnupg2,gnutls-bin,apt-transport-https,ca-certificates $components"

if [ "$distro" = "devuan" ]; then
        usekeyring="--keyring-packages devuan-keyring,debian-keyring,debian-archive-keyring"
        mirror='http://packages.devuan.org/merged'
        bootstrapopts="--merged-usr $dsusekeyring --variant=minbase --include=busybox-syslogd,gnupg2,gnutls-bin,apt-transport-https,ca-certificates $components"
elif [ "$distro" = "ubuntu" ]; then
        usekeyring="--keyring-packages ubuntu-archive-keyring,debian-keyring,debian-archive-keyring"
        mirror='http://archive.ubuntu.com/ubuntu/'
        bootstrapopts="--merged-usr $dsusekeyring --variant=minbase --include=busybox-syslogd,gnupg2,gnutls-bin,apt-transport-https,ca-certificates $components"
        components=$( [ ! -z "$nonfree" ] && echo "--components=\"main,restricted,universe,multiverse\"" || echo "" )
        archiveareas=$( [ ! -z "$nonfree" ] && echo "--archive-areas=\"main,restricted,universe,multiverse\"" || echo "" )
        distromode="--mode ubuntu"
fi

if [ ! -z "$components" ]; then
        echo "WARNING: USING NON-FREE COMPONENTS! $components"
        echo "$bootstrapopts"
        sleep 5
fi

make import-keys

lb config noauto \
    -b iso-hybrid \
    --apt aptitude \
    --debian-installer live \
    --system live \
    $useproxy \
    $usekeyring \
    -d unstable \
    --updates no \
    --parent-distribution unstable \
    --debootstrap-options "$bootstrapopts" \
    --initsystem sysvinit \
    $archiveareas \
    $nosource \
    $harden \
    --image-name "$image_prename$is_harden$non_free$customized" \
    $distromode \
    "$@" \
    --parent-mirror-bootstrap "$mirror" \
    --security false \
    --mirror-bootstrap "$mirror"
