#! /usr/bin/env bash

set -e

if [ -f auto/common ]; then
        . auto/common
fi

rm -rf ./iso

docker cp $image_prename-build-$distro:/home/livebuilder/hoarder-live/auto/common ./auto/common
docker cp $image_prename-build-$distro:/home/livebuilder/hoarder-live/$image_prename$customized$is_harden$serverdist$non_free-$distro-amd64.hybrid.iso ./iso
docker cp $image_prename-build-$distro:/home/livebuilder/hoarder-live/$image_prename$customized$is_harden$serverdist$non_free-$distro-amd64.files ./iso
docker cp $image_prename-build-$distro:/home/livebuilder/hoarder-live/$image_prename$customized$is_harden$serverdist$non_free-$distro-amd64.contents ./iso
docker cp $image_prename-build-$distro:/home/livebuilder/hoarder-live/$image_prename$customized$is_harden$serverdist$non_free-$distro-amd64.hybrid.iso.zsync ./iso
docker cp $image_prename-build-$distro:/home/livebuilder/hoarder-live/$image_prename$customized$is_harden$serverdist$non_free-$distro-amd64.packages ./iso
