#! /usr/bin/env bash

set -e

if [ -f paths.sh ]; then
        . paths.sh
fi

scp "$user_name"@"$host_name":"$dev_path/auto/common" auto/common

if [ -f auto/common ]; then
        . auto/common
fi



mkdir -p "./iso-$distro"

scp "$user_name"@"$host_name":"$dev_path/iso-$distro/$image_prename$customized$is_harden$serverdist$non_free$persist-$distro-amd64.hybrid.iso" "./iso-$distro"
scp "$user_name"@"$host_name":"$dev_path/iso-$distro/$image_prename$customized$is_harden$serverdist$non_free$persist-$distro-amd64.files" "./iso-$distro"
scp "$user_name"@"$host_name":"$dev_path/iso-$distro/$image_prename$customized$is_harden$serverdist$non_free$persist-$distro-amd64.contents" "./iso-$distro"
scp "$user_name"@"$host_name":"$dev_path/iso-$distro/$image_prename$customized$is_harden$serverdist$non_free$persist-$distro-amd64.hybrid.iso.zsync" "./iso-$distro"
scp "$user_name"@"$host_name":"$dev_path/iso-$distro/$image_prename$customized$is_harden$serverdist$non_free$persist-$distro-amd64.packages" "./iso-$distro"
