#! /usr/bin/env bash

set -e

if [ -f paths.sh ]; then
        . paths.sh
fi

scp dev@dev:"$dev_path/auto/common" auto/common

if [ -f auto/common ]; then
        . auto/common
fi



rm -rf ./iso && mkdir ./iso/

scp dev@dev:"$dev_path/iso/$image_prename$customized$is_harden$serverdist$non_free-$distro-amd64.hybrid.iso" ./iso/
scp dev@dev:"$dev_path/iso/$image_prename$customized$is_harden$serverdist$non_free-$distro-amd64.files" ./iso/
scp dev@dev:"$dev_path/iso/$image_prename$customized$is_harden$serverdist$non_free-$distro-amd64.contents" ./iso/
scp dev@dev:"$dev_path/iso/$image_prename$customized$is_harden$serverdist$non_free-$distro-amd64.hybrid.iso.zsync" ./iso/
scp dev@dev:"$dev_path/iso/$image_prename$customized$is_harden$serverdist$non_free-$distro-amd64.packages" ./iso/
