FROM tv-build-debian
ARG distro="devuan"
ARG nonfree=""
ARG hardened=""
ARG customize=""
ENV distro="devuan"
ENV nonfree=""
ENV hardened=""
ENV customize=""
RUN chown -R livebuilder:livebuilder /home/livebuilder/hoarder-live
USER livebuilder
COPY Makefile /home/livebuilder/hoarder-live/Makefile
COPY config.mk /home/livebuilder/hoarder-live/config.mk
COPY includes /home/livebuilder/hoarder-live/includes/
COPY auto /home/livebuilder/hoarder-live/auto/
COPY keyrings/ /home/livebuilder/hoarder-live/keyrings/
CMD make build
