FROM live-build-ubuntu
COPY keyrings/ keyrings/
COPY Makefile /home/livebuilder/hoarder-live/Makefile
COPY config.mk /home/livebuilder/hoarder-live/config.mk
COPY includes /home/livebuilder/hoarder-live/includes
RUN make docker-init
USER root
COPY auto /home/livebuilder/hoarder-live/auto
RUN make clean
USER livebuilder
RUN make config
RUN make libre
RUN make custom
RUN make skel
RUN make permissive-user
RUN make packages
USER root
