FROM tv-build-ubuntu
ARG nonfree=""
ARG hardened=""
ARG customize=""
RUN chown -R livebuilder:livebuilder /home/livebuilder/
COPY auto /home/livebuilder/hoarder-live/auto
COPY config.mk /home/livebuilder/hoarder-live/config.mk
COPY includes /home/livebuilder/hoarder-live/includes
COPY keyrings/ keyrings/
COPY Makefile /home/livebuilder/hoarder-live/Makefile
USER livebuilder
RUN make config
USER root
CMD make build
