FROM tv-build-ubuntu
ARG distro="ubuntu"
ARG nonfree=""
ARG hardened=""
ARG custom=""
ENV distro="ubuntu"
ENV nonfree=""
ENV hardened=""
ENV custom=""
COPY Makefile /home/livebuilder/hoarder-live/Makefile
COPY config.mk /home/livebuilder/hoarder-live/config.mk
COPY includes /home/livebuilder/hoarder-live/includes/
COPY auto /home/livebuilder/hoarder-live/auto/
COPY keyrings/ /home/livebuilder/hoarder-live/keyrings/
RUN chown -R livebuilder:livebuilder /home/livebuilder/hoarder-live
WORKDIR /home/livebuilder/hoarder-live/
USER livebuilder
CMD make build
