FROM tv-build-devuan
ARG distro="devuan"
ARG nonfree=""
ARG hardened=""
ARG customize=""
ENV distro="devuan"
ENV nonfree=""
ENV hardened=""
ENV customize=""
COPY Makefile /home/livebuilder/hoarder-live/Makefile
COPY config.mk /home/livebuilder/hoarder-live/config.mk
COPY includes /home/livebuilder/hoarder-live/includes/
COPY auto /home/livebuilder/hoarder-live/auto/
COPY keyrings/ /home/livebuilder/hoarder-live/keyrings/
RUN chown -R livebuilder:livebuilder /home/livebuilder/hoarder-live
WORKDIR /home/livebuilder/hoarder-live/
USER livebuilder
RUN make build-nochroot
CMD bash
